# Generated by Django 3.1 on 2020-09-11 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200908_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='comments',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.comments'),
            preserve_default=False,
        ),
    ]
