# Generated by Django 3.1 on 2020-09-11 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200911_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.comments'),
        ),
    ]
