# Generated by Django 3.1 on 2020-09-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200911_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='winner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='won', to='auctions.user'),
            preserve_default=False,
        ),
    ]
