# Generated by Django 3.1 on 2020-09-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200912_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctionlistings'),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='auctions.comments'),
        ),
    ]
