# Generated by Django 3.1 on 2020-09-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200914_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='current_on',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.auctionlistings'),
            preserve_default=False,
        ),
    ]
