# Generated by Django 3.1 on 2020-09-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200917_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='current_on',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.auctionlistings'),
        ),
    ]
