# Generated by Django 3.1 on 2020-09-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200918_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='current_on',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.auctionlistings'),
            preserve_default=False,
        ),
    ]
