# Generated by Django 3.1 on 2020-09-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200918_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.RemoveField(
            model_name='bids',
            name='current_on',
        ),
    ]
