# Generated by Django 3.1 on 2020-09-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200919_0453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlistings',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'get_latest_by': ['updated_at']},
        ),
    ]
