# Generated by Django 3.1 on 2020-09-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200919_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'ordering': ['amount']},
        ),
    ]
