# Generated by Django 3.1 on 2020-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200920_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
