# Generated by Django 3.1 on 2020-09-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200920_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlistings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
    ]
