# Generated by Django 3.1 on 2020-09-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200920_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
